name: NPM Publish Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_CODEBUILD_REGION }}

      - name: Build and Deploy
        uses: Verto-FX/aws-codebuild-run-build@1c1c04c8ab8ef96c9bcf92b02939c768f85d6877
        with:
          project-name: one-build-main
